Make Makefile portable
haampie/libtree pull request #72
Opened 2022-03-19 17:53 UTC by ismaell

- Just include Make.user directly
- Replace SunPro-style pattern rule by suffix rule; neither can merge
  targets into a single call, so no point in using $?
- Replace unportable $^ with a variable.
- Replace wildcard+sort with a call to ls, also for portability.

2022-03-19 20:47 UTC, ismaell commented
This enables using `bmake`, not portable enough for `fmake` or `smake`.

2022-03-19 23:30 UTC, haampie requested changes

2022-03-19 23:30 UTC, haampie commented on Makefile
> +	ls -1 -d tests/* | while read dir; do \
```suggestion
	find tests -type d -mindepth 1 -maxdepth 1 | while read -r dir; do \
```

squashes https://github.com/koalaman/shellcheck/wiki/SC2012 and https://github.com/koalaman/shellcheck/wiki/SC2162

2022-03-20 14:23 UTC, merged

2022-03-20 15:43 UTC, haampie commented
Are you packaging libtree for some new platform?

2022-03-20 16:18 UTC, ismaell commented
Thanks. Yes, I just packaged it for SourceMage, but I can package for several systems.

2022-03-20 17:23 UTC, haampie commented
Great! I'll wait for a few more changes or a bit of time before tagging new patch versions.